# Generated by Django 3.2.8 on 2021-11-01 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_test_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 11, 1, 16, 20, 31, 408581)),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 20, 31, 438263)),
        ),
    ]
