# Generated by Django 3.2.8 on 2021-11-01 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211101_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 56, 30, 675830))),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 56, 30, 645608)),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 56, 30, 675207)),
        ),
    ]
