# Generated by Django 3.2.8 on 2021-11-01 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20211101_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 57, 19, 896755)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 57, 19, 867472)),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 57, 19, 896135)),
        ),
    ]
