# Generated by Django 3.2.8 on 2021-11-01 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20211101_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 59, 39, 429594)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 59, 39, 399384)),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 22, 59, 39, 428953)),
        ),
    ]
