# Generated by Django 3.2.8 on 2021-11-01 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20211101_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charger',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 3, 19, 541065)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 3, 19, 512106)),
        ),
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 23, 3, 19, 540443)),
        ),
    ]
